services:
  bot:
    image: ghcr.nju.edu.cn/lagrangedev/lagrange.onebot:edge
    pull_policy: always
    restart: always
    volumes:
      - ./bot:/app/data
    depends_on:
      - ws

  ws:
    image: python:3.12-slim
    restart: always
    command: bash -c "pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt && python server.py"
    working_dir: /app
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DOUBAO_API_KEY: ${DOUBAO_API_KEY}
      DOUBAO_MODEL: ${DOUBAO_MODEL}
    volumes:
      - ./ws:/app
    ports:
      - 127.0.0.1:8811:8000

  python:
    build: 
      context: ./python
    restart: always
    environment:
      # SANIC_KEEP_ALIVE: False
      SANIC_REQUEST_TIMEOUT: 10
      SANIC_RESPONSE_TIMEOUT: 10
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
      restart_policy:
        condition: on-failure
