services:
  bot:
    image: ghcr.io/konatadev/lagrange.onebot:edge
    restart: always
    volumes:
      - ./bot:/app/data
    depends_on:
      - ws

  ws:
    image: python:3.12-slim
    restart: always
    command: bash -c "pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt && python server.py"
    working_dir: /app
    volumes:
      - ./ws:/app

  python:
    build: 
      context: ./python
    restart: always
    environment:
      # SANIC_KEEP_ALIVE: False
      SANIC_REQUEST_TIMEOUT: 10
      SANIC_RESPONSE_TIMEOUT: 10
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
      restart_policy:
        condition: on-failure
